### ISSUE TITLE
ElVladimirReborn

### ISSUE THREAD

**Issue by HyunMi027** [AlterEgojQuery/ElBundle#28]
ElVladimirReborn will auto stack e sometimes even if this has been explicitly disabled in the menu, will try to provide more info after this test game

had this issue in laneclear

**Comment by jQueryBase64MyAss** [comment]
ty

**Comment by HyunMi027** [comment]
np, also get a new avatar pls

**Comment by jQueryBase64MyAss** [comment]
No xd
